apiVersion: apps/v1
kind: Deployment
metadata:
  name: dharke-frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dharke-frontend
      version: v1.0
  template:
    metadata:
      labels:
        app: dharke-frontend
        version: v1.0
    spec:
      containers:
      - name: dharke-frontend
        image: aatishsthaa/dharke-frontend:latest
        ports:
        - name: http
          containerPort: 80
