apiVersion: v1
kind: Service
metadata:
  name: dharke-frontend-v1
  namespace: frontend
  labels:
    app: dharke-frontend
    version: v1.0
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: dharke-frontend
    version: v1.0