apiVersion: apps/v1
kind: Deployment
metadata:
  name: dharke-frontend
  namespace: frontend
  labels:
    name: frontend-solid
    version: v1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dharke-frontend-solid
      version: v1.0
  template:
    metadata:
      labels:
        name: dharke-frontend-solid
        version: v1.0
    spec:
      containers:
      - name: dharke-frontend
        image: aatishsthaa/dharke-frontend:latest
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
